package com.baton.slack;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.baton.ai.*; import com.baton.ai.dto.*; import com.baton.common.*; import com.fasterxml.jackson.databind.JsonNode; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor
public class SlackIntegrationService {
 private final SlackConnectionRepository connections; private final SlackSubscriptionRepository subscriptions; private final SlackOAuthStateRepository states; private final SlackImportedMessageRepository imported; private final SlackApiClient api; private final SlackTokenCipher cipher; private final ExternalSourceService sources;
 @Value("${app.slack.client-id:}") private String clientId; @Value("${app.slack.client-secret:}") private String clientSecret; @Value("${app.slack.redirect-uri:http://127.0.0.1:8081/api/v1/integrations/slack/oauth/callback}") private String redirectUri;
 @Transactional public String installUrl(UUID owner){configured();var state=states.save(SlackOAuthState.create(owner));return "https://slack.com/oauth/v2/authorize?client_id="+clientId+"&scope=channels:read,channels:history,groups:read,groups:history&redirect_uri="+url(redirectUri)+"&state="+state.getState();}
 @Transactional public SlackConnection callback(String code,String state){configured();var s=states.findById(state).filter(x->x.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new BusinessException(ErrorCode.SLACK_OAUTH_FAILED));JsonNode n=api.oauth(clientId,clientSecret,code,redirectUri);String team=n.path("team").path("id").asText();var c=connections.findByOwnerIdAndTeamId(s.getOwnerId(),team).orElseGet(()->SlackConnection.create(s.getOwnerId(),team,n.path("team").path("name").asText(),cipher.encrypt(n.path("access_token").asText()),n.path("bot_user_id").asText(),n.path("scope").asText()));c.refresh(n.path("team").path("name").asText(),cipher.encrypt(n.path("access_token").asText()),n.path("bot_user_id").asText(),n.path("scope").asText());states.delete(s);return connections.save(c);}
 @Transactional(readOnly=true) public List<SlackApiClient.Channel> channels(UUID owner,UUID connection){var c=owned(owner,connection);return api.channels(cipher.decrypt(c.getBotToken()));}
 @Transactional public SlackSubscription subscribe(UUID owner,UUID handover,UUID connection,String channelId,String channelName){owned(owner,connection);var s=subscriptions.findByHandoverIdAndConnectionIdAndChannelId(handover,connection,channelId).orElseGet(()->SlackSubscription.create(handover,connection,channelId,channelName));s=subscriptions.save(s);sync(s);return s;}
 @Scheduled(fixedDelayString="${app.slack.sync-interval-ms:60000}",initialDelay=30000) public void scheduledSync(){for(var s:subscriptions.findAllByEnabledTrue()){try{sync(s);}catch(Exception ignored){}}}
 @Transactional public int sync(SlackSubscription s){var c=connections.findById(s.getConnectionId()).orElseThrow();String token=cipher.decrypt(c.getBotToken());var h=api.history(token,s.getChannelId(),s.isBackfillComplete()?s.getOldestTs():null,s.isBackfillComplete()?null:s.getBackfillCursor());int count=0;String newest=s.getOldestTs();for(var m:h.messages()){count+=upsert(c,s,m);if(m.replyCount()>0)for(var r:api.replies(token,s.getChannelId(),m.ts()))if(!r.ts().equals(m.ts()))count+=upsert(c,s,r);if(newest==null||Double.parseDouble(m.ts())>Double.parseDouble(newest))newest=m.ts();}s.synced(newest,s.isBackfillComplete()?null:h.nextCursor());subscriptions.save(s);return count;}
 private int upsert(SlackConnection c,SlackSubscription s,SlackApiClient.Message m){if(m.text()==null||m.text().isBlank())return 0;String hash=hash(m.text());var old=imported.findByHandoverIdAndConnectionIdAndChannelIdAndMessageTs(s.getHandoverId(),c.getId(),s.getChannelId(),m.ts());String link="https://slack.com/archives/"+s.getChannelId()+"/p"+m.ts().replace(".","");Instant at=Instant.ofEpochMilli((long)(Double.parseDouble(m.ts())*1000));if(old.isPresent()){if(old.get().getContentHash().equals(hash))return 0;sources.update(s.getHandoverId(),old.get().getSourceId(),new UpdateExternalSourceRequest("Slack #"+s.getChannelName(),null,link,s.getChannelName(),m.text(),at,true));old.get().changed(hash);return 1;}var result=sources.createSlack(s.getHandoverId(),new CreateSlackMessageRequest(link,"Slack #"+s.getChannelName(),s.getChannelName(),m.text(),at,true));imported.save(SlackImportedMessage.create(s.getHandoverId(),c.getId(),s.getChannelId(),m.ts(),result.source().getId(),hash));return 1;}
 @Transactional public void event(String team,String channel,String subtype,String ts,String text){for(var c:connections.findAllByTeamId(team))for(var s:subscriptions.findAllByConnectionIdAndChannelIdAndEnabledTrue(c.getId(),channel)){var row=imported.findByHandoverIdAndConnectionIdAndChannelIdAndMessageTs(s.getHandoverId(),c.getId(),channel,ts);if("message_deleted".equals(subtype)){row.ifPresent(m->{sources.delete(s.getHandoverId(),m.getSourceId());imported.delete(m);});}else upsert(c,s,new SlackApiClient.Message(ts,text,"",0));}}
 private SlackConnection owned(UUID owner,UUID id){return connections.findById(id).filter(c->c.getOwnerId().equals(owner)).orElseThrow(()->new BusinessException(ErrorCode.HANDOVER_FORBIDDEN));}
 private void configured(){if(clientId.isBlank()||clientSecret.isBlank())throw new BusinessException(ErrorCode.SLACK_NOT_CONFIGURED);}
 private String url(String s){return java.net.URLEncoder.encode(s,StandardCharsets.UTF_8);} private String hash(String s){try{return Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
