package com.baton.slack;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import com.fasterxml.jackson.databind.*; import lombok.RequiredArgsConstructor;
@RestController @RequestMapping("/api/v1/integrations/slack/events") @RequiredArgsConstructor
public class SlackEventController {
 private final SlackIntegrationService service; private final ObjectMapper json; @Value("${app.slack.signing-secret:}") private String secret;
 @PostMapping public ResponseEntity<?> receive(@RequestHeader("X-Slack-Request-Timestamp") String timestamp,@RequestHeader("X-Slack-Signature") String signature,@RequestBody String body)throws Exception{if(!valid(timestamp,signature,body))return ResponseEntity.status(401).build();JsonNode root=json.readTree(body);if("url_verification".equals(root.path("type").asText()))return ResponseEntity.ok(Map.of("challenge",root.path("challenge").asText()));JsonNode e=root.path("event");if("message".equals(e.path("type").asText())&&!e.has("bot_id")){String subtype=e.path("subtype").asText();String ts=e.path("ts").asText();String text=e.path("text").asText();if("message_changed".equals(subtype)){ts=e.path("message").path("ts").asText();text=e.path("message").path("text").asText();}else if("message_deleted".equals(subtype))ts=e.path("deleted_ts").asText();service.event(root.path("team_id").asText(),e.path("channel").asText(),subtype,ts,text);}return ResponseEntity.ok(Map.of("ok",true));}
 boolean valid(String timestamp,String signature,String body)throws Exception{if(secret.isBlank()||Math.abs(Instant.now().getEpochSecond()-Long.parseLong(timestamp))>300)return false;Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));String expected="v0="+HexFormat.of().formatHex(mac.doFinal(("v0:"+timestamp+":"+body).getBytes(StandardCharsets.UTF_8)));return MessageDigest.isEqual(expected.getBytes(StandardCharsets.UTF_8),signature.getBytes(StandardCharsets.UTF_8));}
}
