package com.baton.slack;
import java.net.URI; import java.net.http.*; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*;
import org.springframework.stereotype.Component; import com.fasterxml.jackson.databind.*;
@Component public class SlackApiClient {
 private final ObjectMapper json; private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build(); SlackApiClient(ObjectMapper json){this.json=json;}
 JsonNode oauth(String id,String secret,String code,String redirect){return form("https://slack.com/api/oauth.v2.access",null,Map.of("client_id",id,"client_secret",secret,"code",code,"redirect_uri",redirect));}
 List<Channel> channels(String token){JsonNode n=get("https://slack.com/api/conversations.list?types=public_channel,private_channel&exclude_archived=true&limit=200",token);List<Channel> out=new ArrayList<>();n.path("channels").forEach(c->out.add(new Channel(c.path("id").asText(),c.path("name").asText(),c.path("is_private").asBoolean(),c.path("is_member").asBoolean())));return out;}
 History history(String token,String channel,String oldest,String cursor){String u="https://slack.com/api/conversations.history?channel="+enc(channel)+"&limit=15"+(oldest==null?"":"&oldest="+enc(oldest))+(cursor==null||cursor.isBlank()?"":"&cursor="+enc(cursor));JsonNode n=get(u,token);List<Message> list=new ArrayList<>();n.path("messages").forEach(m->{if("message".equals(m.path("type").asText())&&!m.has("subtype"))list.add(new Message(m.path("ts").asText(),m.path("text").asText(),m.path("user").asText(),m.path("reply_count").asInt()));});return new History(list,n.path("response_metadata").path("next_cursor").asText());}
 List<Message> replies(String token,String channel,String ts){JsonNode n=get("https://slack.com/api/conversations.replies?channel="+enc(channel)+"&ts="+enc(ts)+"&limit=15",token);List<Message> out=new ArrayList<>();n.path("messages").forEach(m->out.add(new Message(m.path("ts").asText(),m.path("text").asText(),m.path("user").asText(),0)));return out;}
 private JsonNode get(String url,String token){try{var r=http.send(HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(15)).header("Authorization","Bearer "+token).GET().build(),HttpResponse.BodyHandlers.ofString());return checked(r);}catch(Exception e){throw new IllegalStateException("Slack API failed",e);}}
 private JsonNode form(String url,String token,Map<String,String> data){try{String body=data.entrySet().stream().map(e->enc(e.getKey())+"="+enc(e.getValue())).reduce((a,b)->a+"&"+b).orElse("");var b=HttpRequest.newBuilder(URI.create(url)).header("Content-Type","application/x-www-form-urlencoded");if(token!=null)b.header("Authorization","Bearer "+token);return checked(http.send(b.POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString()));}catch(Exception e){throw new IllegalStateException("Slack API failed",e);}}
 private JsonNode checked(HttpResponse<String> r)throws Exception{JsonNode n=json.readTree(r.body());if(r.statusCode()/100!=2||!n.path("ok").asBoolean())throw new IllegalStateException("Slack API: "+n.path("error").asText("HTTP "+r.statusCode()));return n;}
 private static String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}
 public record Channel(String id,String name,boolean privateChannel,boolean member){} public record Message(String ts,String text,String user,int replyCount){} public record History(List<Message> messages,String nextCursor){}
}
